[package]
name = "error_calculations"
version = "0.1.0"
authors = ["chris m <christophermoran@ucsb.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13"
inline-python = "0.5.1"